services:
  backend:
    build:
      context: ../Backend
    working_dir: /app
    volumes:
      - ../Backend:/app
    ports:
      - "3000:3000"
    command: npm run start:dev
    environment:
      - NODE_ENV=development
  frontend:
    build:
      context: ../Frontend
    working_dir: /app
    volumes:
      - ../Frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
  ai:
    build:
      context: ../AI
    working_dir: /app
    volumes:
      - ../AI:/app
    ports:
      - "5000:5000"
    command: python3 main.py
    environment:
      - PYTHONUNBUFFERED=1
